In [1]:
import pandas as pd
import numpy as np

# !pip install pycountry
import pycountry

In [2]:
file_path = "/content/drive/MyDrive/Portfolio - Data Analysis | BI/Job Salary/job_salaries.csv"

In [3]:
df = pd.read_csv(file_path)

In [4]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,EN,FT,Analytics Engineer,43000,USD,43000,HU,0,HU,L
1,2023,SE,FT,Data Scientist,239900,USD,239900,US,100,US,M
2,2023,SE,FT,Data Scientist,159900,USD,159900,US,100,US,M
3,2023,EN,FT,Data Analyst,162240,USD,162240,US,0,US,M
4,2023,EN,FT,Data Analyst,47840,USD,47840,US,0,US,M

In [5]:
df.dtypes

work_year              int64
experience_level      object
employment_type       object
job_title             object
salary                 int64
salary_currency       object
salary_in_usd          int64
employee_residence    object
remote_ratio           int64
company_location      object
company_size          object
dtype: object

In [6]:
# EN: Entry-level / Junior
# MI: Mid-level / Intermediate
# SE: Senior-level / Expert
# EX: Executive-level / Director

exp_level_values = {'EN':'Junior',
                    'MI':'Intermediate',
                    'SE':'Expert',
                    'EX':'Director'}

# PT: Part-time
# FT: Full-time
# CT: Contract
# FL: Freelance

employment_type_values = {'PT':'Part-time',
                         'FT':'Full-time',
                         'CT':'Contract',
                         'FL':'Freelance'}

# S: less than 50 employees (small)
# M: 50 to 250 employees (medium)
# L: more than 250 employees (large)

company_size_values = {'S':'Small',
                       'M':'Medium',
                       'L':'Large'}

In [7]:
df['experience_level'] = df['experience_level'].replace(exp_level_values)
df['employment_type'] = df['employment_type'].replace(employment_type_values)
df['company_size'] = df['company_size'].replace(company_size_values)
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,Junior,Full-time,Analytics Engineer,43000,USD,43000,HU,0,HU,Large
1,2023,Expert,Full-time,Data Scientist,239900,USD,239900,US,100,US,Medium
2,2023,Expert,Full-time,Data Scientist,159900,USD,159900,US,100,US,Medium
3,2023,Junior,Full-time,Data Analyst,162240,USD,162240,US,0,US,Medium
4,2023,Junior,Full-time,Data Analyst,47840,USD,47840,US,0,US,Medium
...,...,...,...,...,...,...,...,...,...,...,...
10198,2020,Expert,Full-time,Data Scientist,412000,USD,412000,US,100,US,Large
10199,2021,Intermediate,Full-time,Principal Data Scientist,151000,USD,151000,US,100,US,Large
10200,2020,Junior,Full-time,Data Scientist,105000,USD,105000,US,100,US,Small
10201,2020,Junior,Contract,Business Data Analyst,100000,USD,100000,US,100,US,Large
10202,2021,Expert,Full-time,Data Science Manager,7000000,INR,94665,IN,50,IN,Large

In [8]:
# Create a mapping of country ISO codes to country names
country_mapping = {country.alpha_2: country.name for country in pycountry.countries}

# Assuming 'df' is your DataFrame and 'country_column' is the name of the column with the ISO country codes
df['company_location'] = df['company_location'].map(country_mapping)
df['employee_residence'] = df['employee_residence'].map(country_mapping)

# Now 'df' will have the full country names instead of the ISO codes
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,Junior,Full-time,Analytics Engineer,43000,USD,43000,Hungary,0,Hungary,Large
1,2023,Expert,Full-time,Data Scientist,239900,USD,239900,United States,100,United States,Medium
2,2023,Expert,Full-time,Data Scientist,159900,USD,159900,United States,100,United States,Medium
3,2023,Junior,Full-time,Data Analyst,162240,USD,162240,United States,0,United States,Medium
4,2023,Junior,Full-time,Data Analyst,47840,USD,47840,United States,0,United States,Medium
...,...,...,...,...,...,...,...,...,...,...,...
10198,2020,Expert,Full-time,Data Scientist,412000,USD,412000,United States,100,United States,Large
10199,2021,Intermediate,Full-time,Principal Data Scientist,151000,USD,151000,United States,100,United States,Large
10200,2020,Junior,Full-time,Data Scientist,105000,USD,105000,United States,100,United States,Small
10201,2020,Junior,Contract,Business Data Analyst,100000,USD,100000,United States,100,United States,Large
10202,2021,Expert,Full-time,Data Science Manager,7000000,INR,94665,India,50,India,Large

In [9]:
df['work_model'] = df['remote_ratio'].apply(lambda x: 'In-person' if x == 0 else ('Remote' if x == 100 else 'Hybrid'))
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,work_model
0,2023,Junior,Full-time,Analytics Engineer,43000,USD,43000,Hungary,0,Hungary,Large,In-person
1,2023,Expert,Full-time,Data Scientist,239900,USD,239900,United States,100,United States,Medium,Remote
2,2023,Expert,Full-time,Data Scientist,159900,USD,159900,United States,100,United States,Medium,Remote
3,2023,Junior,Full-time,Data Analyst,162240,USD,162240,United States,0,United States,Medium,In-person
4,2023,Junior,Full-time,Data Analyst,47840,USD,47840,United States,0,United States,Medium,In-person
...,...,...,...,...,...,...,...,...,...,...,...,...
10198,2020,Expert,Full-time,Data Scientist,412000,USD,412000,United States,100,United States,Large,Remote
10199,2021,Intermediate,Full-time,Principal Data Scientist,151000,USD,151000,United States,100,United States,Large,Remote
10200,2020,Junior,Full-time,Data Scientist,105000,USD,105000,United States,100,United States,Small,Remote
10201,2020,Junior,Contract,Business Data Analyst,100000,USD,100000,United States,100,United States,Large,Remote
10202,2021,Expert,Full-time,Data Science Manager,7000000,INR,94665,India,50,India,Large,Hybrid

In [10]:
df.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
work_model            0
dtype: int64

In [11]:
new_file_path_csv = "/content/drive/MyDrive/Portfolio - Data Analysis | BI/Job Salary/job_salaries_treated.csv"
new_file_path_excel = "/content/drive/MyDrive/Portfolio - Data Analysis | BI/Job Salary/job_salaries_treated.xlsx"

In [12]:
df.to_csv(new_file_path_csv, index=False)

In [13]:
df.to_excel(new_file_path_excel, index=False)